package com.coderedrobotics.scouting;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class GUI extends javax.swing.JFrame {

    private int lastNumber;
    private Team currentTeam;
    private boolean saved = true;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lookupButton = new javax.swing.JButton();
        teamNumber = new javax.swing.JTextField();
        defensePanel = new javax.swing.JPanel();
        portcullis = new javax.swing.JCheckBox();
        chivalDeFrise = new javax.swing.JCheckBox();
        moat = new javax.swing.JCheckBox();
        ramparts = new javax.swing.JCheckBox();
        drawbridge = new javax.swing.JCheckBox();
        sallyPort = new javax.swing.JCheckBox();
        rockWall = new javax.swing.JCheckBox();
        roughTerrain = new javax.swing.JCheckBox();
        lowBar = new javax.swing.JCheckBox();
        towerPanel = new javax.swing.JPanel();
        lowGoal = new javax.swing.JCheckBox();
        challenge = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        highGoal = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        climbing = new javax.swing.JSlider();
        climbSpeed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        made = new javax.swing.JSpinner();
        missed = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        scoringPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        disposition = new javax.swing.JSlider();
        broken = new javax.swing.JCheckBox();
        doesntFollowRules = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        fudge = new javax.swing.JSpinner();
        manualOverride = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        autonomousPanel = new javax.swing.JPanel();
        autonCanReach = new javax.swing.JCheckBox();
        autonLowGoal = new javax.swing.JCheckBox();
        autonHighGoal = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        autonPortcullis = new javax.swing.JCheckBox();
        autonChivalDeFrise = new javax.swing.JCheckBox();
        autonMoat = new javax.swing.JCheckBox();
        autonDrawbridge = new javax.swing.JCheckBox();
        autonSallyPort = new javax.swing.JCheckBox();
        autonRamparts = new javax.swing.JCheckBox();
        autonRoughTerrain = new javax.swing.JCheckBox();
        autonLowBar = new javax.swing.JCheckBox();
        autonRockWall = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("2016 Scouting App");

        lookupButton.setText("Lookup...");
        lookupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookupButtonActionPerformed(evt);
            }
        });

        teamNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNumberActionPerformed(evt);
            }
        });

        defensePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Defenses"));

        portcullis.setText("Portcullis");

        chivalDeFrise.setText("Chival De Frise");

        moat.setText("Moat");

        ramparts.setText("Ramparts");

        drawbridge.setText("Drawbridge");

        sallyPort.setText("Sally Port");

        rockWall.setText("Rock Wall");

        roughTerrain.setText("Rough Terrain");

        lowBar.setText("Low Bar");

        javax.swing.GroupLayout defensePanelLayout = new javax.swing.GroupLayout(defensePanel);
        defensePanel.setLayout(defensePanelLayout);
        defensePanelLayout.setHorizontalGroup(
            defensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defensePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(defensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portcullis)
                    .addComponent(chivalDeFrise)
                    .addComponent(moat)
                    .addComponent(ramparts)
                    .addComponent(drawbridge)
                    .addComponent(sallyPort)
                    .addComponent(rockWall)
                    .addComponent(roughTerrain)
                    .addComponent(lowBar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        defensePanelLayout.setVerticalGroup(
            defensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defensePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(portcullis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chivalDeFrise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ramparts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drawbridge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sallyPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rockWall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roughTerrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lowBar))
        );

        towerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tower"));

        lowGoal.setText("Low Goal");

        challenge.setText("Can Challenge");

        jLabel1.setText("High Goal");

        highGoal.setMajorTickSpacing(1);
        highGoal.setMaximum(10);
        highGoal.setPaintLabels(true);
        highGoal.setPaintTicks(true);
        highGoal.setSnapToTicks(true);

        jLabel2.setText("Climbing");

        climbing.setMajorTickSpacing(1);
        climbing.setMaximum(10);
        climbing.setPaintLabels(true);
        climbing.setPaintTicks(true);
        climbing.setSnapToTicks(true);

        jLabel3.setText("Climb Speed:");

        jLabel4.setText("Made");

        jLabel11.setText("Missed");

        javax.swing.GroupLayout towerPanelLayout = new javax.swing.GroupLayout(towerPanel);
        towerPanel.setLayout(towerPanelLayout);
        towerPanelLayout.setHorizontalGroup(
            towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(towerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(towerPanelLayout.createSequentialGroup()
                        .addComponent(lowGoal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(climbSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(towerPanelLayout.createSequentialGroup()
                        .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(highGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(climbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(towerPanelLayout.createSequentialGroup()
                        .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(challenge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(made, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(missed, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap())
        );
        towerPanelLayout.setVerticalGroup(
            towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(towerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(climbSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(lowGoal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(challenge)
                    .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(towerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(made, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(missed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(highGoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(climbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        scoringPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        jLabel8.setText("Disposition");

        disposition.setMajorTickSpacing(1);
        disposition.setMaximum(3);
        disposition.setMinimum(1);
        disposition.setPaintLabels(true);
        disposition.setPaintTicks(true);
        disposition.setSnapToTicks(true);
        disposition.setValue(2);

        broken.setText("Broken");

        doesntFollowRules.setText("Doesn't follow game rules");

        jLabel9.setText("Manual Ranking Fudge:");

        jLabel10.setText("Man. Rank Override:");

        javax.swing.GroupLayout scoringPanelLayout = new javax.swing.GroupLayout(scoringPanel);
        scoringPanel.setLayout(scoringPanelLayout);
        scoringPanelLayout.setHorizontalGroup(
            scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disposition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(scoringPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fudge, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scoringPanelLayout.createSequentialGroup()
                        .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doesntFollowRules)
                            .addComponent(jLabel8)
                            .addComponent(broken))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(scoringPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(manualOverride, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        scoringPanelLayout.setVerticalGroup(
            scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scoringPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(broken)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doesntFollowRules)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(manualOverride, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(scoringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fudge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        autonomousPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Autonomous"));

        autonCanReach.setText("Can Reach");

        autonLowGoal.setText("Low goal");

        autonHighGoal.setText("High goal");

        autonPortcullis.setText("Portcullis");

        autonChivalDeFrise.setText("Chival De Frise");

        autonMoat.setText("Moat");

        autonDrawbridge.setText("Drawbridge");

        autonSallyPort.setText("Sally Port");

        autonRamparts.setText("Ramparts");

        autonRoughTerrain.setText("Rough Terrain");

        autonLowBar.setText("Low Bar");

        autonRockWall.setText("Rock Wall");

        jLabel5.setText("Can cross:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autonPortcullis)
                    .addComponent(autonChivalDeFrise)
                    .addComponent(autonMoat)
                    .addComponent(autonRamparts)
                    .addComponent(autonDrawbridge)
                    .addComponent(autonSallyPort)
                    .addComponent(autonRockWall)
                    .addComponent(autonRoughTerrain)
                    .addComponent(autonLowBar)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(autonPortcullis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autonChivalDeFrise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autonMoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autonRamparts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autonDrawbridge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autonSallyPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autonRockWall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autonRoughTerrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autonLowBar)
                .addContainerGap())
        );

        javax.swing.GroupLayout autonomousPanelLayout = new javax.swing.GroupLayout(autonomousPanel);
        autonomousPanel.setLayout(autonomousPanelLayout);
        autonomousPanelLayout.setHorizontalGroup(
            autonomousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autonomousPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autonomousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autonCanReach)
                    .addComponent(autonLowGoal)
                    .addComponent(autonHighGoal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        autonomousPanelLayout.setVerticalGroup(
            autonomousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autonomousPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autonomousPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(autonomousPanelLayout.createSequentialGroup()
                        .addComponent(autonCanReach)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(autonomousPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(autonLowGoal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(autonHighGoal)
                        .addGap(189, 189, 189))))
            .addGroup(autonomousPanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane1.setViewportView(notes);

        jLabel6.setText("Notes:");

        jLabel7.setText("Team Number:");

        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Robot Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(autonomousPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(defensePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(towerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoringPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lookupButton)
                        .addGap(120, 120, 120)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teamNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookupButton)
                    .addComponent(teamNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(saveButton)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scoringPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(towerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(defensePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(autonomousPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            if (currentTeam != null) {
                Team t = currentTeam;
                t.setPortcullis(portcullis.isSelected());
                t.setChivalDeFrise(chivalDeFrise.isSelected());
                t.setMoat(moat.isSelected());
                t.setRamparts(ramparts.isSelected());
                t.setDrawBridge(drawbridge.isSelected());
                t.setSallyPort(sallyPort.isSelected());
                t.setRockWall(rockWall.isSelected());
                t.setRoughTerrain(roughTerrain.isSelected());
                t.setLowBar(lowBar.isSelected());
                t.setLowGoal(lowGoal.isSelected());
                t.setChallenge(challenge.isSelected());
                t.setClimbingSpeed(Integer.parseInt(climbSpeed.getText()));
                t.setHighGoalScore(highGoal.getValue());
                t.setClimbingScore(climbing.getValue());
                t.setAutoReach(autonCanReach.isSelected());
                t.setAutoLowGoal(autonLowGoal.isSelected());
                t.setAutoHighGoal(autonHighGoal.isSelected());
                t.setAutoPortcullis(autonPortcullis.isSelected());
                t.setAutoChivalDeFrise(autonChivalDeFrise.isSelected());
                t.setAutoMoat(autonMoat.isSelected());
                t.setAutoRamparts(autonRamparts.isSelected());
                t.setAutoDrawbridge(autonDrawbridge.isSelected());
                t.setAutoSallyPort(autonSallyPort.isSelected());
                t.setAutoRockWall(autonRockWall.isSelected());
                t.setAutoRoughTerrain(autonRoughTerrain.isSelected());
                t.setAutoLowbar(autonLowBar.isSelected());
                t.setNotes(notes.getText());
                t.setBroken(broken.isSelected());
                t.setDisposition(disposition.getValue());
                t.setDoesntFollowRules(doesntFollowRules.isSelected());
                t.setRankingFudge(Integer.parseInt(fudge.getValue().toString()));
                t.setManualRankOverride(Integer.parseInt(manualOverride.getValue().toString()));
                t.setMade((int) made.getValue());
                t.setMissed((int) missed.getValue());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter an integer climb speed.", "Number Format Exception", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Serialization.writeMemory(Competition.getInstance());
            saved = true;
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void teamNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNumberActionPerformed
        if (!saved) {
            int reply = JOptionPane.showConfirmDialog(this, "You have not saved since switching to this team.\nAre you sure you want to continue?",
                    "Continue without saving?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (reply == JOptionPane.NO_OPTION) {
                teamNumber.setText(String.valueOf(lastNumber));
                return;
            }
        }
        saved = false;

        int number;
        try {
            number = Integer.parseInt(teamNumber.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid team number", "Number Format Exception", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!Competition.getInstance().teamExists(number)) {
            int reply = JOptionPane.showConfirmDialog(this, "Team " + number + " does not exist yet.\nDo you want to create it?",
                    "Create team", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (reply == JOptionPane.NO_OPTION) {
                teamNumber.setText(String.valueOf(lastNumber));
                return;
            }
        }

        lastNumber = number;
        Team t = Competition.getInstance().getTeam(number);
        currentTeam = t;

        portcullis.setSelected(t.canPortcullis());
        chivalDeFrise.setSelected(t.canChivalDeFrise());
        moat.setSelected(t.canMoat());
        ramparts.setSelected(t.canRamparts());
        drawbridge.setSelected(t.canDrawBridge());
        sallyPort.setSelected(t.canSallyPort());
        rockWall.setSelected(t.canRockWall());
        roughTerrain.setSelected(t.canRoughTerrain());
        lowBar.setSelected(t.canLowBar());
        lowGoal.setSelected(t.canLowGoal());
        challenge.setSelected(t.canChallenge());
        climbSpeed.setText(String.valueOf(t.getClimbingSpeed()));
        highGoal.setValue(t.getHighGoalScore());
        climbing.setValue(t.getClimbingScore());
        autonCanReach.setSelected(t.canAutoReach());
        autonLowGoal.setSelected(t.canAutoLowGoal());
        autonHighGoal.setSelected(t.canAutoHighGoal());
        autonPortcullis.setSelected(t.canAutoPortcullis());
        autonChivalDeFrise.setSelected(t.canAutoChivalDeFrise());
        autonMoat.setSelected(t.canAutoMoat());
        autonRamparts.setSelected(t.canAutoRamparts());
        autonDrawbridge.setSelected(t.canAutoDrawbridge());
        autonSallyPort.setSelected(t.canAutoSallyPort());
        autonRockWall.setSelected(t.canAutoSallyPort());
        autonRoughTerrain.setSelected(t.canAutoRoughTerrain());
        autonLowBar.setSelected(t.canAutoLowbar());
        notes.setText(t.getNotes());
        broken.setSelected(t.isBroken());
        doesntFollowRules.setSelected(t.doesntFollowRules());
        fudge.setValue(t.getRankingFudge());
        manualOverride.setValue(t.getManualRankOverride());
        disposition.setValue(t.getDisposition());
        made.setValue(t.getMade());
        missed.setValue(t.getMissed());
    }//GEN-LAST:event_teamNumberActionPerformed

    private void lookupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookupButtonActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            new LookupGUI().setVisible(true);
        });
    }//GEN-LAST:event_lookupButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int number;
        try {
            number = Integer.parseInt(teamNumber.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid team number", "Number Format Exception", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new RobotImage(number).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the System Default look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            Competition.setInstance(Serialization.readMemoryIn());
            Network net = new Network();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autonCanReach;
    private javax.swing.JCheckBox autonChivalDeFrise;
    private javax.swing.JCheckBox autonDrawbridge;
    private javax.swing.JCheckBox autonHighGoal;
    private javax.swing.JCheckBox autonLowBar;
    private javax.swing.JCheckBox autonLowGoal;
    private javax.swing.JCheckBox autonMoat;
    private javax.swing.JCheckBox autonPortcullis;
    private javax.swing.JCheckBox autonRamparts;
    private javax.swing.JCheckBox autonRockWall;
    private javax.swing.JCheckBox autonRoughTerrain;
    private javax.swing.JCheckBox autonSallyPort;
    private javax.swing.JPanel autonomousPanel;
    private javax.swing.JCheckBox broken;
    private javax.swing.JCheckBox challenge;
    private javax.swing.JCheckBox chivalDeFrise;
    private javax.swing.JTextField climbSpeed;
    private javax.swing.JSlider climbing;
    private javax.swing.JPanel defensePanel;
    private javax.swing.JSlider disposition;
    private javax.swing.JCheckBox doesntFollowRules;
    private javax.swing.JCheckBox drawbridge;
    private javax.swing.JSpinner fudge;
    private javax.swing.JSlider highGoal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lookupButton;
    private javax.swing.JCheckBox lowBar;
    private javax.swing.JCheckBox lowGoal;
    private javax.swing.JSpinner made;
    private javax.swing.JSpinner manualOverride;
    private javax.swing.JSpinner missed;
    private javax.swing.JCheckBox moat;
    private javax.swing.JTextArea notes;
    private javax.swing.JCheckBox portcullis;
    private javax.swing.JCheckBox ramparts;
    private javax.swing.JCheckBox rockWall;
    private javax.swing.JCheckBox roughTerrain;
    private javax.swing.JCheckBox sallyPort;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel scoringPanel;
    private javax.swing.JTextField teamNumber;
    private javax.swing.JPanel towerPanel;
    // End of variables declaration//GEN-END:variables
}
